version: 2
jobs:
  building_artifacts:
    docker:
      - image: alpine:latest
    steps:
      - run: echo "Generating artifacts"

      - image: alpine:latest
    steps:
      - run: echo "Generating image"

  unit_tests:
    docker:
      - image: alpine:latest
    steps:
      - run: echo "Testing"

  integrated_tests:
    docker:
      - image: alpine:latest
    steps:
      - run: echo "More Testing"

  release_tests:
    docker:
      - image: alpine:latest
    steps:
      - run: echo "More, More Testing"

  pre_release:
    docker:
      - image: alpine:latest
    steps:
      - run: echo "Generating pre-release"

  deploying_staging:
    docker:
      - image: alpine:latest
    steps:
      - run: echo "deploying pre-release to Staging"

  release:
    docker:
      - image: alpine:latest
    steps:
      - run: echo "Generating release"

  deploying_production:
    docker:
      - image: alpine:latest
    steps:
      - run: echo "Deploying release to Production"

workflows:
  version: 2
  flow:
    jobs:
      - building_artifacts
      - unit_tests:
          requires:
            - building_artifacts
      - integrated_tests:
          requires:
            - building_artifacts
      - release_tests:
          requires:
            - building_artifacts
      - pre_release:
          requires:
            - unit_tests
            - integrated_tests
            - release_tests
          filters:
            branches:
              only: master
      - deploying_staging:
          requires:
            - pre_release
          filters:
            branches:
              only: master
      - release:
          type: approval
          requires:
            - deploying_staging
          filters:
            branches:
              only: master
      - deploying_production:
          requires:
            - release
          filters:
            branches:
              only: master