version: 2
jobs:
  building_artifacts:
    docker:
      - image: alpine:latest
    steps:
      - run: echo "Generating artifacts"

  building_image:
    docker:
      - image: alpine:latest
    steps:
      - run: echo "Generating image"

  tests:
    docker:
      - image: alpine:latest
    steps:
      - run: echo "Testing"

  pre_release:
    docker:
      - image: alpine:latest
    steps:
      - run: echo "Generating pre-release"

  deploying_staging:
    docker:
      - image: alpine:latest
    steps:
      - run: echo "deploying pre-release to Staging"

  release:
    docker:
      - image: alpine:latest
    steps:
      - run: echo "Generating release"

  deploying_production:
    docker:
      - image: alpine:latest
    steps:
      - run: echo "Deploying release to Production"

workflows:
  version: 2
  flow:
    jobs:
      - building_artifacts
      - building_image:
          requires:
            - building_artifacts
      - tests
      - pre_release:
          requires:
            - tests
      - deploying_staging:
          requires:
            - pre_release
      - release:
          requires:
            - deploying_staging
      - deploying_production:
          requires:
            - release